### ISSUE TITLE
Windows spring-boot run command should be "mvnw spring-boot:run" instead "./mvnw spring-boot:run"

### ISSUE THREAD

**Issue by bdemers** [okta-samples/okta-spring-boot-sample#2]
Moved from: okta/okta-cli/issues#60
by: @KostiantynDrozd-okta

When I created a spring-boot app with command `okta start`, I see message:
```
Run this application with:
    ./mvnw spring-boot:run
```
But command for windows to run looks like:
    
`mvnw spring-boot:run`

Do we need to change that message?

**Comment by mraible** [comment]
Is it possible to detect the OS and print out the appropriate message?

**Comment by bdemers** [comment]
not really... currently the CLI just prints out whatever is in the `directions` field: https://github.com/okta-samples/okta-spring-boot-sample/blob/master/.okta/sample-config.yaml#L6

We might be able to do some quick templating though, and process the `directions` string as a mustache template 🤔

**Comment by mraible** [comment]
I would just change it to print out `mvn spring-boot:run`. Those that want to use the Maven wrapper should be smart enough to change the command.

**Comment by mraible** [comment]
Closing since the message now reads `mvn spring-boot:run`.

https://github.com/okta-samples/okta-spring-boot-sample/blob/main/.okta/sample-config.yaml#L12
