### ISSUE TITLE
Add logout feature for OIDC login

### ISSUE THREAD

**Issue by mraible** [okta-samples/okta-spring-boot-sample#39]
Quarkus and Micronaut samples have this feature.

**Comment by bdemers** [comment]
💯 I was demoing this app the other day, and it's a little too basic, I love a good hello world app, but this one needs a bit more  to it, possibly a simplified version of this: https://github.com/okta/samples-java-spring/tree/master/okta-hosted-login
(with the logout configured)

**Comment by mraible** [comment]
This is complete.
